version: '3.6'
services:
  java:
    build: ./java
    ports:
      - 8080:8080
    tty: true
    volumes: 
      - ../:/usr/src
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh:/etc/.ssh
  redis:
    build: ./redis
    ports:
      - 6379:6379